---
linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 42
  cyclop:
    max-complexity: 42
  maligned:
    suggest-new: true
  dupl:
    threshold: 200
  goconst:
    min-len: 2
    min-occurrences: 3
  gci:
    local-prefixes: github.com/haproxytech/client-native/v2

linters:
  enable-all: true
  disable:
    - testpackage
    - goconst
    - wsl
